### ISSUE TITLE
加入新的表情包：alu

### ISSUE THREAD

**Issue by tnrzy** [GamerNoTitle/Valine-Magic#1]
提出新的issue！（下面的复选框如果要选择的话请把中括号内的空格改成`x`哦！）

- [x] 加入新的表情包

- [ ] 表情显示不出来（如显示为customxxx）

---

如果你想加入新的表情包，但是你没有图片，有相关的网站，请你在下面填写↓

https://cloud.panjunwen.com/alu/(表情名字)

["吐.png","喷血.png","狂汗.png","不说话.png","汗.png","坐等.png","献花.png","不高兴.png","中刀.png","害羞.png","皱眉.png","小眼睛.png","中指.png","尴尬.png","瞅你.png","想一想.png","中枪.png","得意.png","肿包.png","扇耳光.png","亲亲.png","惊喜.png","脸红.png","无所谓.png","便便.png","愤怒.png","蜡烛.png","献黄瓜.png","内伤.png","投降.png","观察.png","看不见.png","击掌.png","抠鼻.png","邪恶.png","看热闹.png","口水.png","抽烟.png","锁眉.png","装大款.png","吐舌.png","无奈.png","长草.png","赞一个.png","呲牙.png","无语.png","阴暗.png","不出所料.png","咽气.png","期待.png","高兴.png","吐血倒地.png","哭泣.png","欢呼.png","黑线.png","喜极而泣.png","喷水.png","深思.png","鼓掌.png","暗地观察.png"]

**Comment by tnrzy** [comment]
待会儿写个C++，整合一下~~（不会py之痛）~~

**Comment by GamerNoTitle** [comment]
已加入alu系列表情包！
列表在https://gamernotitle.coding.net/p/Valine-BQB1/d/Valine-BQB1/git/tree/master/alu
里面的README里面有
