### ISSUE TITLE
表情无法显示了

### ISSUE THREAD

**Issue by pmy0721** [GamerNoTitle/Valine-Magic#18]
提出新的issue！（下面的复选框如果要选择的话请把中括号内的空格改成`x`哦！）

- [ ] 加入新的表情包
- [ ] 表情显示不出来（如显示为customxxx）
- [ ] 用在Valine上有BUG（不包括显示不出来的问题哦）
- [ ] 你有更好的建议

---

### 加入新的表情包

如果你想加入新的表情包，并且你有图片，请你打包并发到[admin@bili33.top](mailto:admin@bili33.top)

如果你想加入新的表情包，但是你没有图片，有相关的网站，请你在下面填写↓  例子[#1](https://github.com/GamerNoTitle/Valine-Magic/issues/1)

表情链接：

表情列表：[]

---

### 表情显示不出来

请你在下面列出显示不出来的表情名（具体表现为`xxx`，点击显示不出来的图标的时候在valine里面会写作`:xxx:`，就是这个），请按下面这种方式写，并说明你使用的是`MiniValine`还是`Valine`（请将你使用的系统名字左边的中括号中的空格改成`x`：

- [ ] MiniValine
- [x] Valine

显示不出来的表情：(以前能显示的表情都显示不出来了)
 :weibo:
 :bilibiliHotKey:
 :QQ:
 :dingtalk:
 :Tieba-New:

目前只有CDN链接：https://gamernotitle.coding.net/p/ValineCDN/d/ValineCDN/git/raw/master/    可以显示少部分表情，
其他链接均已失效
![KAWZBOXD`I$D9$EM@4)X2BC](https://user-images.githubusercontent.com/85235079/181501645-9df430c1-4698-49dc-8ad3-0b2ffc89ed00.png)

调用代码：
![6$F8S4M68W)0 C2QO5R 6`R](https://user-images.githubusercontent.com/85235079/181502476-4db1447b-b9eb-4ea4-84cb-850bab01b2da.png)

---

### 用在Valine/MiniValine上有BUG

请你在下面说明是什么BUG哦~顺带请你告诉我要如何复现Thanks♪(･ω･)ﾉ

---

### 我有更好的建议

请把你的建议写在下面哦~我保证每一条建议我都会认真看并考虑是否可行的(\*╹▽╹\*)

**Comment by GamerNoTitle** [comment]
emmmm，用最底下那个我的自建反代是可以的
你现在用的是\*.bili33.top，这个域名在备案
建议换成cdn.bilicdn.tk

**Comment by GamerNoTitle** [comment]
![Screenshot_2022-07-29-17-13-12-269_com microsoft emmx](https://user-images.githubusercontent.com/28426291/181726952-1fb30cf0-eff4-4264-a1e0-7a726af1b732.jpg)
这个是我用个人反代的那个链接访问的，可以正常显示

**Comment by pmy0721** [comment]
> emmmm，用最底下那个我的自建反代是可以的 你现在用的是*.bili33.top，这个域名在备案 建议换成cdn.bilicdn.tk

好的谢谢
