### ISSUE TITLE
关于Readme的一些问题

### ISSUE THREAD

**Issue by CCJohny** [GamerNoTitle/Valine-Magic#2]
我实测了一下，如果cdn地址为空，会默认为微博表情的cdn，然后再加上你的表情链接，所以应该是要改cdn为你的表情连接仓库，然后表情包单独上文件名（所以你可能要把所有表情包整理到一起🙃

**Comment by CCJohny** [comment]
还要谢谢你之前的魔改和现在提供的表情！😀

**Comment by GamerNoTitle** [comment]
好的 我知道了 我看看晚上整合一下
感谢提醒

**Comment by GamerNoTitle** [comment]
因为我现在还没有使用Valine1.4.5+ 所以我以为Valine的逻辑是跟之前一样
CDN直接留空然后链接接上自己的地址就可以（手动捂脸）

**Comment by CCJohny** [comment]
🆗

**Comment by GamerNoTitle** [comment]
已经修改好啦 如果可以的话你可以试试CDN的效果并反馈给我嘛？

**Comment by CCJohny** [comment]
可以~谢谢你😀




CCJFun
ccjfun@qq.com



&nbsp;
