### ISSUE TITLE
希望添加微博的表情包狗头啥的，还有滑稽

### ISSUE THREAD

**Issue by 1134451886** [GamerNoTitle/Valine-Magic#3]

**Comment by GamerNoTitle** [comment]
有链接之类的给我看看嘛？（不用微博所以对微博的东西不是很清楚……）

**Comment by 1134451886** [comment]
我网上搜了一圈没有找到打包的链接……

**Comment by GamerNoTitle** [comment]
![](https://i.loli.net/2020/05/01/O2gnDeszGNp8TFx.png)
这种？

**Comment by 1134451886** [comment]
对！

**Comment by GamerNoTitle** [comment]
我去试试弄下来 如果顺利的话今晚能更

**Comment by 1134451886** [comment]
坐等更新！

**Comment by GamerNoTitle** [comment]
我加上了微博表情包了 你可以到这里查看
https://github.com/GamerNoTitle/Valine-Magic/tree/master/weibo
还有需要的表情包欢迎提出:)
