### ISSUE TITLE
希望表情包支持 MiniValine 格式

### ISSUE THREAD

**Issue by MHuiG** [GamerNoTitle/Valine-Magic#8]
提出新的issue！（下面的复选框如果要选择的话请把中括号内的空格改成`x`哦！）

- [ ] 加入新的表情包
- [ ] 表情显示不出来（如显示为customxxx）
- [ ] 用在Valine上有BUG（不包括显示不出来的问题哦）
- [x] 你有更好的建议

---

### 加入新的表情包

如果你想加入新的表情包，并且你有图片，请你打包并发到[admin@bili33.top](mailto:admin@bili33.top)

如果你想加入新的表情包，但是你没有图片，有相关的网站，请你在下面填写↓  例子[#1](https://github.com/GamerNoTitle/Valine-Magic/issues/1)

表情链接：

表情列表：[]

---

### 表情显示不出来

请你在下面列出显示不出来的表情名（具体表现为`customxxx`，点击显示不出来的图标的时候在valine里面会写作`:customxxx:`，就是这个），请按下面这种方式写：

custom1

custom2

...

---

### 用在Valine上有BUG

请你在下面说明是什么BUG哦~顺带请你告诉我要如何复现Thanks♪(･ω･)ﾉ

---

### 我有更好的建议

请把你的建议写在下面哦~我保证每一条建议我都会认真看并考虑是否可行的(\*╹▽╹\*)

https://github.com/MiniValine/docs/blob/main/en/Options.md#how-to-customize-emoticons

**Comment by GamerNoTitle** [comment]
已添加支持，欢迎使用
如果有Bug请反馈Thanks♪(･ω･)ﾉ
